# File: application.yml
# Path: your-portfolio-service-project/src/main/resources/application.yml

server:
  port: 8090 # Unique port for the Portfolio Service

spring:
  application:
    name: PORTFOLIO-SERVICE # Eureka Service ID
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_db # Or your MySQL URL
    username: portfolio1_user # Replace with your PostgreSQL/MySQL username
    password: postgres # Replace with your PostgreSQL/MySQL password
    driver-class-name: org.postgresql.Driver # Or com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 'update' is good for development, 'validate' or 'none' for production
    show-sql: true # Log SQL statements to console
    properties:
      hibernate:
        format_sql: true # Format SQL logs for readability

# Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # Address of your Eureka Server
  instance:
    hostname: localhost # Hostname for Eureka registration
    instance-id: ${spring.application.name}:${random.value} # Unique ID for Eureka