# File: application.yml
# Path: your-auth-service-project/src/main/resources/application.yml

server:
  port: 8092

spring:
  application:
    name: AUTH-SERVICE
  # ... other spring configs ...

# JWT Configuration
jwt:
  secret: aSecureRandomSecretKeyForJWTGenerationAndValidationThatIsLongEnoughAndComplex
  expiration: 3600000


user-service:
  url: USER-SERVICE

# Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    # ADD THIS LINE:
    instance-id: ${spring.application.name}:${random.value} # Gives a unique ID like AUTHENTICATION-SERVICE:1a2b3c
    # You could also try: instance-id: ${spring.application.name}:${server.port}
    # Or even: instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}