# File: application-eureka.yml
# Path: your-user-service-project/src/main/resources/application-eureka.yml

spring:
  application:
    name: NOTIFICATION-SERVICE # This ID is crucial for Eureka and API Gateway routing
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # Address of your Eureka Server
  instance:
    hostname: localhost