# File: application-eureka.yml
# Path: your-user-service-project/src/main/resources/application-eureka.yml

spring:
  application:
    name: USER-SERVICE # This ID is crucial for Eureka and API Gateway routing

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost